// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Entity
{
    public partial class Image
    {
        public int Id { get; set; }
        public int? ProductId { get; set; }
        public string FileName { get; set; }
        public string OriginalFileName { get; set; }
        public int? ImageVersion { get; set; }

        public virtual Product Product { get; set; }
    }
}