// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Entities.Entity
{
    public partial class uspGetGenderResult
    {
        public int GenderId { get; set; }
        public string GenderName { get; set; }
    }
}
